# Generated by Django 3.0.7 on 2020-10-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_document_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='knowledge_image'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
