# Generated by Django 3.0.7 on 2020-10-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='knowledge_image'),
        ),
    ]
