# Generated by Django 3.0.7 on 2020-10-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
    ]
