# Generated by Django 3.0.7 on 2020-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology.', 'Technology'), ('Reserach', 'Reserach'), ('Story', 'Story'), ('Update', 'Update'), ('Policy', 'Policy'), ('Scheme', 'Scheme')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='knowledge_image'),
        ),
    ]
