# Generated by Django 3.0.7 on 2020-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201016_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.FileField(null=True, upload_to='knowledge_image'),
        ),
    ]
