# Generated by Django 3.0.7 on 2020-10-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201016_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Reserach', 'Reserach'), ('Story', 'Story'), ('Update', 'Update'), ('Policy', 'Policy'), ('Scheme', 'Scheme')], max_length=20),
        ),
    ]
