# Generated by Django 3.0.7 on 2020-10-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
