# Generated by Django 3.0.7 on 2020-09-24 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0028_cart_fpo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from1', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('phone', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='store.Fpo_Registeration')),
            ],
        ),
    ]
