# Generated by Django 3.0.7 on 2020-09-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20200918_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='by_fpo',
            field=models.IntegerField(null=True),
        ),
    ]
