# Generated by Django 3.0.7 on 2020-09-24 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_cart_by_fpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cartuser_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='date_added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
