# Generated by Django 3.0.7 on 2020-09-24 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20200924_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='by_fpo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='store.Fpo_Registeration'),
        ),
    ]
