# Generated by Django 3.0.7 on 2020-09-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20200924_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fpo_id',
            field=models.IntegerField(null=True),
        ),
    ]
