# Generated by Django 3.0.7 on 2020-10-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='store.Fpo_Registeration'),
        ),
    ]
