# Generated by Django 3.0.7 on 2020-10-03 15:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_service_service_by1'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_unit',
            field=models.CharField(choices=[('Hrs.', 'Hrs.'), ('Netting', 'Netting'), ('Day', 'Day')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
