# Generated by Django 3.0.7 on 2020-10-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20201003_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo_Registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_username', models.CharField(max_length=50)),
                ('ngo_name', models.CharField(max_length=50)),
                ('ngo_area', models.CharField(max_length=500)),
                ('ngo_email', models.CharField(max_length=500)),
                ('ngo_mobile1', models.IntegerField(null=True)),
                ('ngo_mobile2', models.IntegerField(null=True)),
                ('ngo_description', models.TextField()),
                ('area_pincode', models.IntegerField(null=True)),
                ('ngo_img', models.ImageField(upload_to='images/NGO')),
            ],
        ),
    ]
