# Generated by Django 3.0.7 on 2020-10-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_ngo_registeration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_by',
        ),
        migrations.AddField(
            model_name='service',
            name='service_by',
            field=models.ManyToManyField(default=True, to='store.Ngo_Registeration'),
        ),
    ]
