# Generated by Django 3.0.7 on 2020-10-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20201008_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_by',
        ),
        migrations.AddField(
            model_name='service',
            name='service_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='store.Ngo_Registeration'),
        ),
    ]
