# Generated by Django 3.0.7 on 2020-10-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_serviceforcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_certificate',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_distric',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_pancard',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_registeration_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_registered_with',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_state',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
