# Generated by Django 3.0.7 on 2020-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20201015_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo_registeration',
            name='ngo_certificate',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='ngo_registeration',
            name='ngo_distric',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ngo_registeration',
            name='ngo_pancard',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='ngo_registeration',
            name='ngo_registeration_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ngo_registeration',
            name='ngo_registered_with',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ngo_registeration',
            name='ngo_state',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
