# Generated by Django 3.0.7 on 2020-10-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
